---
title: "<center><div class='mytitle'>Sumarstörf fyrir nema hjá BioPol á Skagaströnd, sumarið 2020</div></center>"
author: "<center><div class='mysubtitle'>Heiti verkefnis: Sjálfvirk dýptarstýring umhverfismæla í hafi og skráningar í gagnagrunn</div></center>"
output:
  html_document:
    toc: false
pagetitle: BioPol Sumarstörf    
css: styles.css
---


<div class="mycontent">

<br>

[English below](#summer)

<br>

__Sumarstörf fyrir tvo nema__ í raunvísindum eru í boði hjá [BioPol](https://biopol.is/) á Skagaströnd. Samstarfsaðili er [Náttúrustofa Norðurlands vestra](https://www.nnv.is/) sem hefur höfuðstöðvar á Sauðárkróki. 

Störfin fela í sér talsverða forritun og þrívíddarprentun. Markmiðið er að smíða mælitæki fyrir sjómælingar (CTD; selta hitastig og dýpi) með innbyggðri dýptarstýringu og sendi fyrir gögn.

* **Nemi 1**: Smíða CTD bauju eftir [fyrirliggjandi teikningum](https://github.com/OceanographyforEveryone/OpenCTD) með þeim breytingum að baujan innihaldi tölvu- og flotbúnað sem hannaður er ásamt nema 2.
* **Nemi 2**: Setja upp hugbúnað og vélbúnað, stofna gagnagrunn og skrifa forrit til þess að lesa upplýsingar úr mælum og skrá í gagnagrunninn annars vegar og til að stýra flotbúnaði hins vegar.

Umsóknarfrestur er til og með **10. maí** nk. Umsóknir með upplýsingum um menntun, starfsreynslu og meðmælendur berist BioPol ehf., Einbúastíg 2, 545 Skagaströnd eða valtyr@biopol.is og halldor@biopol.is.

Nánari upplýsingar veitir Valtýr Sigurðsson í síma 846-5996 eða valtyr@biopol.is.

# Verkefnið
Vöktun á sjávarhita og öðrum umhverfisþáttum sjávar gisin hér við land, sem og annars staðar, og mælingar á lagskiptingu sjávar fátíðar. Slíkar sýnatökur eru kostnaðarsamar en til að minnka kostnað má framkvæma þess háttar mælingar með sjálfvirkum hætti. 

Sjálfvirkar CTD baujur eru ekki nýjar af nálinni og ekki stýring á flotkrafti þeirra heldur. Um 900 [flotstýrðar baujur frá Argo](http://www.argo.ucsd.edu/How_Argo_floats.html) fljóta um heimshöfin og senda gögn um gervihnetti. Slíkar baujur eru mjög dýrar og því hefur fólk reynt að finna aðrar lausnir (t.d. verkefnið [„OceanographyforEveryone“](https://github.com/OceanographyforEveryone/OpenCTD)). Okkar verkefni myndi sækja í kistu slíkra verkefna en þar eru teikningar og kóði í boði ásamt stuðningi notendasamfélagsins sem er opið öllum og mjög gefandi. 

Ef vel gengur mun búnaðurinn nýtast við sjórannsóknir fyrir lítinn hluta þess kostnaðar sem slíkar rannsóknir bera venjulega. Nemarnir sjá um að framkvæma þetta verkefni með þeim búnaði, forritum og efni sem þeir telja best með eins hagkvæmum hætti og kostur er.
Starfinu fylgja tíðar sýnatökur og úrvinnsla tölulegra gagna. Verkefni nemandans fælist í að gera hluta gagnaöflunar sjálfvirka.

# Aðstaðan
Biopol hefur skrifstofu- og tilraunaaðstöðu en í 40 mínútna akstursfjarlægð er [Fablab á Sauðárkróki](https://www.fablab.is/starfsstodvar/saudarkrokur/) þar sem aðgangur er að þrívíddarprentara. Biopol hefur bíl sem nemarnir geta fengið til ferða tengdum verkefninu. Reglulegar sýnatökuferðir á báti eru farnar á vegum Biopol sem gefa nemunum reynslu af sjómælingum óski þeir þess. 
Umsjónarmaður liðsinnir við vinnu nemanna og í næsta húsi eru bæði véla- og rafmagnsverkstæði en samfélagið á Skagaströnd er fullt velvilja frá greiðviknu fólki. Biopol mun aðstoða nemana við að finna húsnæði til leigu. Umsjónarmaður ber ábyrgð á skilum lokaskýrslu til styrkveitanda (Rannís) sem unnin verður í samstarfi við nemana.

# Verk- og tímaáætlun
* Vikur 1-3:
    + nemi 1) Kaup á búnaði (ef eitthvað vantar), samsetning og 3D-prentun hefst.
    + nemi 2) Kaup á búnaði (ef eitthvað vantar), uppsetning og forritun.
* Vikur 4-9:
    + nemi 1) Tilraunir með búnað í sjó.
    + nemi 2) Uppsetning gagnagrunns og forritun stýringar á flotbúnaði.
* Vikur 10-12:
    + 1 og 2) Lokafrágangur og drög að skýrslu.

# Fyrirhuguð birting eða kynning á niðurstöðum
Niðurstöðurnar verða kynntar fyrir rannsakendum í vistfræði og fleiri náttúruvísindum en einnig hugsanlega fyrir fólki í sjávarútvegi. Verkefnið verður einnig kynnt á vefsíðu Biopol og NNV.

<br><br><br>

# Summer projects {#summer}

_Automatic buoyancy adjustment equipment and data logging system for environmental monitoring_

__Summerjobs for 2 students__ in the natural sciences at [BioPol](https://biopol.is/) Skagaströnd, North-Iceland, in collaboration with [NNV](https://www.nnv.is/). 

The aim is to build a [OpenCTD](https://github.com/OceanographyforEveryone/OpenCTD) project with buoyancy control and data transmition. This includes computer programming, 3D-printing and soldering.

* **Student 1**: Build the [CTD](https://github.com/OceanographyforEveryone/OpenCTD) with modifications to acommodate buoyancy control designed with student 2.
* **Student 2**: Program a device that controls the buoyancy of the CTD. Build programs that send the CTD data and read it into a database. 

Applicants must be interested in computer programming and technology and be able to work independently on these tasks.

Interested applicants should send their resumé to valtyr@biopol.is and halldor@biopol.is **before May 10th**. For further information about the project call Valtýr: 8465996 or email valtyr@biopol.is.

<br><br>

</div>